# Generated by Django 4.2.20 on 2025-03-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc_keylink", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chave",
            old_name="sala",
            new_name="salas",
        ),
        migrations.RenameField(
            model_name="registroentrada",
            old_name="chaves",
            new_name="chave",
        ),
        migrations.RenameField(
            model_name="registrosaida",
            old_name="chaves",
            new_name="chave",
        ),
        migrations.RemoveField(
            model_name="chave",
            name="id",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registroentrada",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registrosaida",
            name="id",
        ),
        migrations.RemoveField(
            model_name="sala",
            name="id",
        ),
        migrations.AddField(
            model_name="chave",
            name="id_chaves",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="id_funcionario",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registroentrada",
            name="id_registro_entrada",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrosaida",
            name="id_registro",
            field=models.CharField(
                default=1, max_length=45, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sala",
            name="id_sala",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cpf_funcionario",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="funcao_funcionario",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="senha",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="tipo_funcionario",
            field=models.CharField(
                choices=[("Quadro", "Quadro"), ("Extra Quadro", "Extra Quadro")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="numero_sala",
            field=models.IntegerField(),
        ),
    ]
