# Generated by Django 4.2.20 on 2025-03-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcc_keylink", "0002_rename_sala_chave_salas_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chave",
            table="chaves",
        ),
        migrations.AlterModelTable(
            name="funcionario",
            table="funcionarios",
        ),
        migrations.AlterModelTable(
            name="sala",
            table="salas",
        ),
    ]
